### ISSUE TITLE
Inaccurate statement in README.MD

### ISSUE THREAD

**Issue by T3CHNOLOG1C** [blawar/lithium#13]
.

**Comment by NovaPhoenix** [comment]
Come on. Now that's just censorship. https://firebird.zone/media/7720913b-8ec6-4de3-9af0-3f0cc3ab8786/Screenshot_20190226_194504.png

**Comment by linktlh** [comment]
From T3CHNOLOG1C:
* You claim that Lithium is Goldleaf's extended evolution, but XorTroll is still working on Goldleaf. If it is a joke referencing Goldleaf's readme, it is a joke in poor taste that may confuse the end user. Otherwise, the statement is just plain incorrect. In addition, in my opinion there is no reason to keep a homebrew app closed source unless you are attempting to hide something.

Since he's trying to hide back lash.

**Comment by joelc608** [comment]
Why are you closing issues Blake?
